name: SitCalcPy
channels:
  - conda-forge
  - anaconda
dependencies:
  - python>=3.10,<4
  - mypy>=0.950,<1
  - pylint>=2.14,<3
  - pydantic>=1.9,<2
  - coverage>=6.4,<7
  - frozendict>=2.3,<3
  - more-itertools>=8.13,<9